{% set version = "1.1-13" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-adephylo
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/adephylo_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/adephylo/adephylo_{{ version }}.tar.gz
  sha256: 2aa132fee9d0a14ac09b0a96af40ac332cb4e13c892908803c335aa7319ca76d

build:
  merge_build_host: true  # [win]
  skip: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ade4 >=1.7_10
    - r-adegenet
    - r-ape
    - r-phylobase
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-ade4 >=1.7_10
    - r-adegenet
    - r-ape
    - r-phylobase

test:
  commands:
    - $R -e "library('adephylo')"           # [not win]
    - "\"%R%\" -e \"library('adephylo')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=adephylo
  license: GPL-2.0-or-later
  summary: Multivariate tools to analyze comparative data, i.e. a phylogeny and some traits measured for each taxa.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: adephylo
# Version: 1.1-11
# Date: 2017-12-18
# Title: Exploratory Analyses for the Phylogenetic Comparative Method
# Author: Thibaut Jombart <t.jombart@imperial.ac.uk>, Stephane Dray <stephane.dray@univ-lyon1.fr>, Anders Ellern Bilgrau <abilgrau@math.aau.dk>
# Maintainer: Stephane Dray <stephane.dray@univ-lyon1.fr>
# Depends: methods, ade4 (>= 1.7-10)
# Imports: phylobase, ape, adegenet
# Description: Multivariate tools to analyze comparative data, i.e. a phylogeny and some traits measured for each taxa.
# License: GPL (>= 2)
# LazyLoad: yes
# RoxygenNote: 6.0.1
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2017-12-18 09:58:25 UTC; stephane
# Repository: CRAN
# Date/Publication: 2017-12-18 16:33:14 UTC
